### ISSUE TITLE
404 during pull request build

### ISSUE THREAD

**Issue by smashwilson** [deconst/content-service#85]
This one's confusing because it's a 404, not a 500. I'm not seeing anything obvious in the logs either.

```
Submitting envelope: [https://github.com/build-7ee8c65bcf/rackerlabs/docs-developer-blog/events/2016-02-24-confoo] .. ok
/usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/response/raise_error.rb:8:in `on_complete': the server responded with status 404 (Faraday::ResourceNotFound)
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/request/retry.rb:110:in `call'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /usr/src/app/.gems/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `put'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:185:in `render_json'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:26:in `block (2 levels) in generate'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:25:in `each'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:25:in `block in generate'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:24:in `each'
    from /usr/src/app/lib/preparermd/plugins/metadata_envelopes.rb:24:in `generate'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/site.rb:280:in `block in generate'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `each'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `generate'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/site.rb:50:in `process'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
    from /usr/src/app/.gems/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
    from /usr/src/app/lib/preparermd.rb:45:in `build'
    from -e:1:in `<main>'
Submitting envelope: [https://github.com/build-7ee8c65bcf/rackerlabs/docs-developer-blog/events/2016-03-17-jupyter-days] .. 
```

**Comment by smashwilson** [comment]
I can see the 404 in nginx:

```
10.187.186.6 - - [15/Mar/2016:02:44:35 +0000] "PUT /content/https%3A%2F%2Fgithub.com%2Fbuild-7ee8c65bcf%2Frackerlabs%2Fdocs-developer-blog%2Fevents%2F2015-11-18-api-strat HTTP/1.1" 204 0 "-" "Faraday v0.9.1"
10.187.186.6 - - [15/Mar/2016:02:44:36 +0000] "PUT /content/https%3A%2F%2Fgithub.com%2Fbuild-7ee8c65bcf%2Frackerlabs%2Fdocs-developer-blog%2Fevents%2F2016-02-24-confoo HTTP/1.1" 204 0 "-" "Faraday v0.9.1"
10.187.186.6 - - [15/Mar/2016:02:44:47 +0000] "PUT /content/https%3A%2F%2Fgithub.com%2Fbuild-7ee8c65bcf%2Frackerlabs%2Fdocs-developer-blog%2Fevents%2F2016-03-17-jupyter-days HTTP/1.1" 404 51 "-" "Faraday v0.9.1"
1
```

But not in the content service logs:

```
{"action":"contentstore","statusCode":204,"apikeyName":"temporary","contentID":"https://github.com/build-7ee8c65bcf/rackerlabs/docs-developer-blog/events/2015-11-18-api-strat","totalReqDuration":245,"message":"Content storage successful.","level":"info","timestamp":"2016-03-15T02:44:35.799Z"}
{"action":"contentstore","statusCode":204,"apikeyName":"temporary","contentID":"https://github.com/build-7ee8c65bcf/rackerlabs/docs-developer-blog/events/2016-02-24-confoo","totalReqDuration":360,"message":"Content storage successful.","level":"info","timestamp":"2016-03-15T02:44:36.219Z"}
```

**Comment by smashwilson** [comment]
Wait, [I found it](https://iad1-10096-kibana.es.objectrocket.com:20096/#/doc/logstash-*/logstash-2016.03.15/logs?id=AVN4KVkEADuSFUPE1-j9&_g=%28%29). It looks like it's a 404 from Cloud Files?

```
Error: rackspace Error (404): Item not found
    at Request._callback (/usr/src/app/node_modules/pkgcloud/lib/pkgcloud/core/base/client.js:157:28)
    at Request.self.callback (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:123:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:1047:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:998:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
```
